package com.itla.vista.administrador;

import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Maria Elena
 */
public class ContenedorPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ContenedorPrincipal
     */
    public ContenedorPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();
        mnCerrarSeccion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnEventos = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenuItem();
        mnInvitaciones = new javax.swing.JMenuItem();
        mnInvitados = new javax.swing.JMenuItem();
        mnPerfilUsuario = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejador Invitaciones");

        jMenu1.setText("Archivo");

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        mnCerrarSeccion.setText("Cerrar Seccion");
        jMenu1.add(mnCerrarSeccion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar");

        mnEventos.setText("Eventos");
        mnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEventosActionPerformed(evt);
            }
        });
        jMenu2.add(mnEventos);

        mnUsuarios.setText("Usuarios");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnUsuarios);

        mnInvitaciones.setText("Invitaciones");
        mnInvitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInvitacionesActionPerformed(evt);
            }
        });
        jMenu2.add(mnInvitaciones);

        mnInvitados.setText("Invitados");
        mnInvitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInvitadosActionPerformed(evt);
            }
        });
        jMenu2.add(mnInvitados);

        mnPerfilUsuario.setText("Perfil Usuario");
        mnPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPerfilUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(mnPerfilUsuario);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Acerca de");

        mnAyuda.setText("Ayuda");
        jMenu7.add(mnAyuda);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEventosActionPerformed
        abrirVentana(new PanelDetalleEvento(this, false), "Eventos");
    }//GEN-LAST:event_mnEventosActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        abrirVentana(new PanelDetalleUsuario(this), "Usuarios");
    }//GEN-LAST:event_mnUsuariosActionPerformed

    private void mnInvitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInvitacionesActionPerformed
        abrirVentana(new PanelCrearInvitacion(this), "Invitacion");
    }//GEN-LAST:event_mnInvitacionesActionPerformed

    private void mnInvitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInvitadosActionPerformed
        abrirVentana(new PanelDetalleInvitado(this), "Invitados");
    }//GEN-LAST:event_mnInvitadosActionPerformed

    private void mnPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPerfilUsuarioActionPerformed
        abrirVentana(new PanelDetallePerfilUsuario(this), "Perfiles De Usuario");
    }//GEN-LAST:event_mnPerfilUsuarioActionPerformed

    public void abrirVentana(JPanel panel, String titulo) {
        JInternalFrame frame = new JInternalFrame(titulo, true, true, true, true);
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ContenedorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        mdiContainer.add(frame);
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContenedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContenedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContenedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContenedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContenedorPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mdiContainer;
    private javax.swing.JMenuItem mnAyuda;
    private javax.swing.JMenuItem mnCerrarSeccion;
    private javax.swing.JMenuItem mnEventos;
    private javax.swing.JMenuItem mnInvitaciones;
    private javax.swing.JMenuItem mnInvitados;
    private javax.swing.JMenuItem mnPerfilUsuario;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnUsuarios;
    // End of variables declaration//GEN-END:variables
}
