package com.itla.vista.administrador;

import com.itla.modelo.Evento;
import com.itla.servicios.ServicioEvento;
import com.itla.vista.comun.AbstractPanel;
import java.awt.Window;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PanelEvento extends AbstractPanel {

    private ServicioEvento servicio = new ServicioEvento();
    private List<Evento> listaEventos;
    private int modificandoIdx = 0;

    public PanelEvento() {
        super();
        initComponents();
    }

    public PanelEvento(Window padre) {
        super();
        this.padre = padre;
        initComponents();
    }

    public PanelEvento(Window padre, List<Evento> eventos) {
        this(padre);
        this.listaEventos = eventos;
        if (eventos != null && eventos.size() == 1) {
            btnGuardarContinuar.setVisible(false);
            cargarData();
        } else if (eventos != null && eventos.size() > 0) {
            cargarData();
        }
    }

    private void cargarData() {
        txtID.setText(String.valueOf(listaEventos.get(modificandoIdx).getId()));
        txtNombre.setText(listaEventos.get(modificandoIdx).getNombre());
        txtFecha.setText(Evento.formato.format(listaEventos.get(modificandoIdx).getFecha()));
        txtUbicacion.setText(listaEventos.get(modificandoIdx).getUbicacion());
        chkActivo.setSelected(listaEventos.get(modificandoIdx).isActivo());
    }

    private boolean validar() {
        boolean valido = true;
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe insertar su nombre");
            valido = false;
        } else if (txtFecha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe insertar la fecha");
            valido = false;
        } else if (txtUbicacion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe insertar su ubicacion");
            valido = false;
        }
        return valido;
    }

    private void guardar() {
        try {
            Evento evento = new Evento(0, chkActivo.isSelected(), txtNombre.getText(), Evento.formato.parse(txtFecha.getText()), txtUbicacion.getText());
            if (!txtID.getText().isEmpty()) {
                evento.setId(Integer.parseInt(txtID.getText()));
            }
            servicio.insertar(evento);
            JOptionPane.showMessageDialog(padre, "Datos insertados correctamente", "Datos insertados", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(PanelEvento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al guardar el registro en la base de datos", "Error guardando", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(PanelEvento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error convertiendo la fecha", "Formato de fecha invalida", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(PanelEvento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error guardando el registro", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtID.setText("");
        txtNombre.setText("");
        txtFecha.setText("");
        txtUbicacion.setText("");
        chkActivo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombre = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        txtUbicacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        panelBotones = new javax.swing.JPanel();
        btnGuardarContinuar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        lbNombre.setText("Nombre:*");

        lbFecha.setText("Fecha:*");

        jLabel3.setText("Ubicacion:*");

        jLabel5.setText("ID:");

        txtID.setEditable(false);
        txtID.setEnabled(false);

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel4.setText("Activo*");

        chkActivo.setSelected(true);
        chkActivo.setText("Activo");

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnGuardarContinuar.setText("Guardar y continuar");
        btnGuardarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContinuarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardarContinuar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombre)
                    .addComponent(jLabel5)
                    .addComponent(lbFecha)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUbicacion)
                    .addComponent(chkActivo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(lbNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbFecha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chkActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //metodo valida formulario
        if (validar()) {
            //metodo para guardar
            guardar();
        }
        //Limpiar los campos
        limpiarCampos();
        //Cerrar la ventana
        padre.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        padre.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContinuarActionPerformed
        //metodo valida formulario
        if (validar()) {
            //metodo para guardar
            guardar();
        }
        //Limpiar los campos
        limpiarCampos();
        if (listaEventos != null && listaEventos.size() > 0 && modificandoIdx < listaEventos.size() - 1) {
            modificandoIdx++;
            cargarData();
        } else if (listaEventos != null && modificandoIdx == listaEventos.size() - 1) {
            padre.dispose();
        }
    }//GEN-LAST:event_btnGuardarContinuarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarContinuar;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
