package com.itla.vista.administrador;

import com.itla.modelo.Evento;
import com.itla.modelo.Invitacion;
import com.itla.modelo.Invitado;
import com.itla.modelo.Sesion;
import com.itla.servicios.ServicioInvitacion;
import com.itla.servicios.ServicioInvitado;
import com.itla.vista.comun.AbstractPanel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Katerina Hernandez
 */
public class PanelCrearInvitacion extends AbstractPanel {
   
    private ServicioInvitacion servicioInvitacion = new ServicioInvitacion();
    private ServicioInvitado servicio = new ServicioInvitado();
    private ArrayList<Invitado> invitados;
    private DefaultTableModel model;
    private Object[] columnasTabla;
    private Evento evento;

    /**
     * Creates new form PanelCrearInvitado
     */
    public PanelCrearInvitacion() {
        refrescar();
        columnasTabla = getColumnsNames();
        model = new javax.swing.table.DefaultTableModel(getData(), columnasTabla) {
            Class[] types = new Class[]{
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean[]{
                true, false, false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        initComponents();
    }

    private Object[] getColumnsNames() {
        return new Object[]{"Seleccionar", "Id", "Nombre", "Apellido", "Telefono", "Direccion", "Sexo", "Activo"};
    }

    private Object[][] getData() {
        Object[][] obj = new Object[invitados.size()][columnasTabla.length];
        for (int i = 0; i < invitados.size(); i++) {
            obj[i][0] = false;
            obj[i][1] = invitados.get(i).getId();
            obj[i][2] = invitados.get(i).getNombre();
            obj[i][3] = invitados.get(i).getApellido();
            obj[i][4] = invitados.get(i).getTelefono();
            obj[i][5] = invitados.get(i).getDireccion();
            obj[i][6] = invitados.get(i).getSexo();
            obj[i][7] = invitados.get(i).isActivo();
        }
        return obj;
    }

    private void cargarData() {
        txtId.setText(Integer.toString(evento.getId()));
        txtFecha.setText(Evento.formato.format(evento.getFecha()));
        txtNombre.setText(evento.getNombre());
        txtUbicacion.setText(evento.getUbicacion());
    }

    private void refrescar() {
        try {
            if (invitados != null) {
                invitados.clear();
            }
            invitados = servicio.seleccionarTodos();
        } catch (SQLException ex) {
            Logger.getLogger(PanelDetalleEvento.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(padre,
                    "Error cargando los datos", "Error cargando los datos", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void refrescarTabla() {
        ((DefaultTableModel) tablaInivtado.getModel()).setDataVector(getData(), columnasTabla);
    }

    private boolean validarSeleccion() {
        for (int fila = 0; fila < tablaInivtado.getModel().getRowCount(); fila++) {
            if ((boolean) tablaInivtado.getModel().getValueAt(fila, 0)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        panelElijaEvento = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelUbicacion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnElegir = new javax.swing.JButton();
        panelEligeInvitado = new javax.swing.JPanel();
        btnAgregarInvitado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInivtado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        panelElijaEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("Elija el evento"));

        labelNombre.setText("Nombre:");

        labelFecha.setText("Fecha:");

        labelUbicacion.setText("Ubicacion:");

        txtNombre.setEditable(false);

        txtFecha.setEditable(false);

        txtUbicacion.setEditable(false);

        labelID.setText("Id:");

        txtId.setEditable(false);

        btnElegir.setText("Elegir evento");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelElijaEventoLayout = new javax.swing.GroupLayout(panelElijaEvento);
        panelElijaEvento.setLayout(panelElijaEventoLayout);
        panelElijaEventoLayout.setHorizontalGroup(
            panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElijaEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelElijaEventoLayout.createSequentialGroup()
                        .addComponent(labelUbicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelElijaEventoLayout.createSequentialGroup()
                        .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelFecha)
                            .addComponent(labelID))
                        .addGap(18, 18, 18)
                        .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha)
                            .addComponent(txtNombre)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElegir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelElijaEventoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFecha, txtNombre, txtUbicacion});

        panelElijaEventoLayout.setVerticalGroup(
            panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElijaEventoLayout.createSequentialGroup()
                .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelElijaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbicacion)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEligeInvitado.setBorder(javax.swing.BorderFactory.createTitledBorder("Elija los invitados"));

        btnAgregarInvitado.setText("Agregar nuevo invitado");
        btnAgregarInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInvitadoActionPerformed(evt);
            }
        });

        tablaInivtado.setModel(model);
        jScrollPane1.setViewportView(tablaInivtado);

        javax.swing.GroupLayout panelEligeInvitadoLayout = new javax.swing.GroupLayout(panelEligeInvitado);
        panelEligeInvitado.setLayout(panelEligeInvitadoLayout);
        panelEligeInvitadoLayout.setHorizontalGroup(
            panelEligeInvitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEligeInvitadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarInvitado)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEligeInvitadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEligeInvitadoLayout.setVerticalGroup(
            panelEligeInvitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEligeInvitadoLayout.createSequentialGroup()
                .addComponent(btnAgregarInvitado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelElijaEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelEligeInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelElijaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEligeInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInvitadoActionPerformed
        JDialog ventana = new JDialog();
        ventana.add(new PanelInvitado(ventana));
        ventana.setModal(true);
        ventana.pack();
        ventana.setVisible(true);
        refrescar();
        refrescarTabla();
    }//GEN-LAST:event_btnAgregarInvitadoActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        JDialog ventana = new JDialog();
        PanelDetalleEvento vent2 = new PanelDetalleEvento(ventana, true);
        ventana.add(vent2);
        ventana.setModal(true);
        ventana.pack();
        ventana.setVisible(true);
        evento = vent2.getEventoSeleccionado();
        if (evento != null) {
            cargarData();
        }
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (evento == null) {
            JOptionPane.showMessageDialog(padre, "Debe seleccionar un evento antes de guardar las invitaciones.", "Seleccione un evento", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarSeleccion()) {
            JOptionPane.showMessageDialog(padre, "Debe seleccionar una o mas personas para guardar las invitaciones", "Elija los invitados", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(Sesion.usuarioLogeado == null){
            JOptionPane.showMessageDialog(padre, "Error faltal del sistema", "No hay usuario logeado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean erroneo = false;
        Invitado invitado = null;
        for (int i = 0; i < tablaInivtado.getModel().getRowCount(); i++) {
            if ((boolean) model.getValueAt(i, 0)) {
                try {
                    //"Id", "Nombre", "Apellido", "Telefono", "Direccion", "Sexo", "Activo"
                    invitado = new Invitado();
                    Vector obj = (Vector) model.getDataVector().get(i);
                    invitado.setId((int) obj.get(1));
                    invitado.setNombre((String) obj.get(2));
                    invitado.setApellido((String) obj.get(3));
                    invitado.setTelefono((String) obj.get(4));
                    invitado.setDireccion((String) obj.get(5));
                    invitado.setSexo((String) obj.get(6));
                    invitado.setActivo((boolean) obj.get(7));
                    servicioInvitacion.insertar(new Invitacion(0, true, null, null, evento, invitado, Sesion.usuarioLogeado));
                    padre.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(PanelCrearInvitacion.class.getName()).log(Level.SEVERE, null, ex);
                    erroneo = true;
                }
            }
        }
        if (erroneo) {
            JOptionPane.showMessageDialog(padre, "Algunos invitados no pudieron ser agregados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInvitado;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelUbicacion;
    private javax.swing.JPanel panelEligeInvitado;
    private javax.swing.JPanel panelElijaEvento;
    private javax.swing.JTable tablaInivtado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
