package com.itla.vista.administrador;

import com.itla.modelo.Invitado;
import com.itla.servicios.ServicioInvitado;
import java.awt.Window;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Elena
 */
public class PanelInvitado extends javax.swing.JPanel {

    private Window padre;
    private ServicioInvitado servicio = new ServicioInvitado();
    private List<Invitado> listaInvitado;
    private int modificandoIdx = 0;

    public PanelInvitado() {
        super();
        initComponents();
    }

    public PanelInvitado(Window padre) {
        super();
        this.padre = padre;
        initComponents();
    }

    public PanelInvitado(Window padre, List<Invitado> invitados) {
        this(padre);
        this.listaInvitado = invitados;
        if (invitados != null && invitados.size() == 1) {
            btnGuardarContinuar.setVisible(false);
            cargarData();
        } else if (invitados != null && invitados.size() > 0) {
            cargarData();
        }
    }

    private void cargarData() {
        txtId.setText(String.valueOf(listaInvitado.get(modificandoIdx).getId()));
        txtNombre.setText(listaInvitado.get(modificandoIdx).getNombre());
        txtApellido.setText(listaInvitado.get(modificandoIdx).getApellido());
        txtTelefono.setText(listaInvitado.get(modificandoIdx).getTelefono());
        txtDireccion.setText(listaInvitado.get(modificandoIdx).getDireccion());
        if(listaInvitado.get(modificandoIdx).getSexo().equalsIgnoreCase("M")){
            rdBtnMasculino.setSelected(true);
        }else{
            rdBtnFemenino.setSelected(true);
        }
        chkActivo.setSelected(listaInvitado.get(modificandoIdx).isActivo());
    }

    public boolean validar() {
        boolean tmp = true;
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Nombre vacio");
            tmp = false;
        }
        if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El Apellido vacio");
            tmp = false;
        }
        if (txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Telefono vacio");
            tmp = false;
        }
        if (txtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo direccion vacio");
            tmp = false;
        }
        if (btnGroupSexo.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion");
            tmp = false;
        }
        return tmp;
    }

    private void guardar() {
        Invitado invitado = new Invitado(0, chkActivo.isSelected(), txtNombre.getText(), txtApellido.getText(), txtTelefono.getText(), txtDireccion.getText(), btnGroupSexo.getSelection().getActionCommand());
        if (!txtId.getText().isEmpty()) {
            invitado.setId(Integer.parseInt(txtId.getText()));
        }
        try {
            servicio.insertar(invitado);
        } catch (SQLException ex) {
            Logger.getLogger(PanelInvitado.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(padre, "Datos insertados correctamente", "Datos insertados", JOptionPane.INFORMATION_MESSAGE);
        txtNombre.requestFocus();

    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        btnGroupSexo.clearSelection();
        chkActivo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        rdBtnMasculino = new javax.swing.JRadioButton();
        rdBtnFemenino = new javax.swing.JRadioButton();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtDireccion = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblAcivo = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        btnGuardarContinuar = new javax.swing.JButton();

        lblNombre.setText("Nombre:*");

        lblApellido.setText("Apellido:*");

        lblTelefono.setText("Telefono:*");

        lblDireccion.setText("Direccion:*");

        lblSexo.setText("Sexo:*");

        rdBtnMasculino.setActionCommand("M");
        btnGroupSexo.add(rdBtnMasculino);
        rdBtnMasculino.setText("Masculino");

        rdBtnFemenino.setActionCommand("F");
        btnGroupSexo.add(rdBtnFemenino);
        rdBtnFemenino.setText("Femenino");

        lblId.setText("Id:");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblAcivo.setText("Activo ");

        chkActivo.setSelected(true);
        chkActivo.setText("Activo");

        btnGuardarContinuar.setText("Guadar y continuar");
        btnGuardarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellido)
                            .addComponent(lblTelefono)
                            .addComponent(lblDireccion)
                            .addComponent(lblId)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcivo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkActivo)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdBtnMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdBtnFemenino))
                            .addComponent(txtId)
                            .addComponent(txtDireccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(rdBtnMasculino)
                    .addComponent(rdBtnFemenino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkActivo)
                    .addComponent(lblAcivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardarContinuar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContinuarActionPerformed
        if (validar()) {
            //metodo para guardar
            guardar();
            //Limpiar los campos
            limpiarCampos();
        }
        if (listaInvitado != null && listaInvitado.size() > 0 && modificandoIdx < listaInvitado.size() - 1) {
            modificandoIdx++;
            cargarData();
        } else if (listaInvitado != null && modificandoIdx == listaInvitado.size() - 1) {
            padre.dispose();
        }
    }//GEN-LAST:event_btnGuardarContinuarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validar()) {
            //metodo para guardar
            guardar();
            //Limpiar los campos
            limpiarCampos();
            //Cerrar la ventana
            padre.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        padre.dispose();
        //System.out.println(boton);
    }//GEN-LAST:event_btnCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarContinuar;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel lblAcivo;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JRadioButton rdBtnFemenino;
    private javax.swing.JRadioButton rdBtnMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
